#web:
#  upload-path: ./admin-server/src/main/resources/static/download/

#spring:
#  datasource:
#    url:jdbc: sqlserver://127.0.0.1:1433;DatabaseName=myDB
#    username: yao
#    password: 000000
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    database: sql_server
#    hibernate:
#      dialect: org.hibernate.dialect.SQLServer2008Dialect

#spring:
  #数据源和jpa配置
#  datasource:
#    user:
#      #数据库相关的配置url  -SSL连接设置为false
#      url: jdbc:mysql://101.132.139.26:3306/myDB?characterEncoding=utf8&useSSL=false
#      #配置用户名
#      username: yao
#      #配置密码
#      password: abc123
#
#
##  #下面为连接池相关配置
#  dbcp2:
#    #初始化连接池大小
#    initial-size: 10
#    #陪住最小连接池数
#    min-idle: 10
#    #配置最大连接池数
#    max-idle: 30
#    #配置获取超时连接的等待时间
#    max-wait-millis: 30000
#    #配置多长时间进行一次检测,检测需要关闭的数据库连接
#    time-between-eviction-runs-millis: 200000
#    #配置连接在连接池的最小生存时间
#    remove-abandoned-on-maintenance: 200000

spring:
  jpa:
    #配置数据库类型
    database: MYSQL
    #配置是否打印sql
    show-sql: true
    #Hibernate相关配置
    hibernate:
      #配置级联等级
#      ddl-auto: update
      second-dialect: org.hibernate.dialect.MySQL5Dialect
      main-dialect: org.hibernate.dialect.SQLServer2008Dialect
#      naming:
#        #命名策略
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    ConnectionTestQuery: SELECT 1
    second:
      #  mysql数据源配置
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://101.132.139.26:3306/myDB?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: yao
      password: abc123
      database: mysql
      configuration:
        maximum-pool-size: 30
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5

    #sqlserver数据源配置
    main:
      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=myDB
      username: sa
      password: '000000'
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      database: sql_server
      configuration:
        maximum-pool-size: 30


  #静态资源访问路径
#  mvc:
#    static-path-pattern: /static/**

#  resources:
#    static-locations: classpath:static/





application:
    #版本
  version: 1.0.0
  #文件上传路径
  profile: D:/projectData/UIData





